version: "3"

services:
  ifconfig:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    environment:
      # - DATABASE_AUTO_UPDATE=true
      # - DATABASE_DIR=/path/to/databases
      # - DNS_CACHE=true
      # - HOST_AUTO=auto.my.domain
      # - HOST_IPV4=ipv4.my.domain
      # - HOST_IPV6=ipv6.my.domain
      # - MAXMIND_ACCOUNT_ID=$MAXMIND_ACCOUNT_ID
      - MAXMIND_LICENSE_KEY=$MAXMIND_LICENSE_KEY
      # - MODE=dev
      # - RATE_LIMIT_INTERVAL=60
      # - RATE_LIMIT=500
      # - SHOW_ABOUT=false
      # - SHOW_FAQ=false
    ports:
      - 8080:80
    tmpfs: /tmpfs
    volumes:
      - .:/var/www:ro
