services:
  ifconfig:
    build:
      context: .
      dockerfile: docker/build/Dockerfile
      target: dev
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file: .env
    ports:
      - 8080:80
    tmpfs: /tmpfs
    volumes:
      - .:/var/www
