version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    environment:
      - mode=DEBUG
      - host_auto=ip.e7d.io
      - host_ipv4=ipv4.e7d.io
      - host_ipv6=ipv6.e7d.io
      # - rate_limit_interval=3
    volumes:
      - .:/var/www:ro
    ports:
      - 5757:80
