version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    environment:
      - mode=DEBUG
      # - host_auto=auto.my.domain
      # - host_ipv4=ipv4.my.domain
      # - host_ipv6=ipv6.my.domain
      # - rate_limit_interval=3
    volumes:
      - .:/var/www:ro
    ports:
      - 5757:80
