<footer>
<?php

use IfConfig\Reader\AsnReader;
use IfConfig\Reader\LocationReader;
use IfConfig\Reader\MacReader;
use Utils\StopwatchService;

function toTime($timestamp): string
{
    return (string) number_format($timestamp * 1000, 2) . "ms";
}

function toStopwatchStats(): string
{
    StopwatchService::get('total')->stop();
    $total = StopwatchService::get('total')->get();
    $dns = StopwatchService::get('dns')->get();
    $database = StopwatchService::get('database')->get();
    // $database += StopwatchService::get('mac-vendors')->get();
    $php = $total - $dns - $database;
    $totalMs = toTime($total);
    $dnsMs = toTime($dns);
    $databaseMs = toTime($database);
    $phpMs = toTime($php);
    return " - <span title=\"PHP: $phpMs&#13;&#10;DNS: $dnsMs&#13;&#10;Database: $databaseMs\">$totalMs</span>";
}

$geodbLatestUpdate = max(LocationReader::getDbFileLatestUpdate(), AsnReader::getDbFileLatestUpdate());
$macVendorsLatestUpdate = MacReader::getDbFileLatestUpdate();
$stopwatch = toStopwatchStats();
if (getenv('SHOW_ABOUT') === 'true') {
    echo '<p><a href="about">About</a>'
        . ($geodbLatestUpdate ? " - GeoIP Database: $geodbLatestUpdate" : '')
        . ($macVendorsLatestUpdate ? " - MAC Vendor Database: $macVendorsLatestUpdate" : '')
        . ($stopwatch ?? '') . '</p>';
}
if ($geodbLatestUpdate) echo '<p>This product includes GeoLite2 data created by MaxMind, available from <a href="https://dev.maxmind.com/geoip" target="_blank" rel="noreferrer">https://www.maxmind.com</a>.</p>';
if ($macVendorsLatestUpdate) echo '<p>This product includes a MAC Vendor JSON database created by MAC Address Lookup, available from <a href="https://maclookup.app/downloads/json-database" target="_blank" rel="noreferrer">https://maclookup.app</a>.</p>';
?>
</footer>
