<?php if (isset($_ENV['HOST_AUTO']) || isset($_ENV['HOST_IPV4']) || isset($_ENV['HOST_IPV6'])) { ?>
    <style>
        .force-ip {
            position: absolute;
            top: 0;
            right: 0;
            margin: 8px;
        }

        .force-ip span+span::before {
            content: " - ";
        }
    </style>
<?php } ?>
<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    li {
        border-top: 1px solid #ddd;
        display: flex;
    }

    li>* {
        overflow: auto;
        padding: 8px;
    }

    label {
        display: inline-block;
        font-weight: bold;
        min-width: 140px;
    }

    span:empty::after {
        content: "-";
    }

    @media (max-width: 640px) {
        li {
            flex-direction: column;
        }

        label {
            padding-bottom: 4px;
        }

        span {
            padding-top: 0;
        }
    }
</style>

<?php if (isset($_ENV['HOST_AUTO']) || isset($_ENV['HOST_IPV4']) || isset($_ENV['HOST_IPV6'])) { ?>
    <div class="force-ip">
        <?php if (isset($_ENV['HOST_AUTO'])) { ?><span><a href="//<?php echo $_ENV['HOST_AUTO'] . $_SERVER['REQUEST_URI']; ?>">Auto</a></span><?php } ?>
        <?php if (isset($_ENV['HOST_IPV4'])) { ?><span><a href="//<?php echo $_ENV['HOST_IPV4'] . $_SERVER['REQUEST_URI']; ?>">IPv4</a></span><?php } ?>
        <?php if (isset($_ENV['HOST_IPV6'])) { ?><span><a href="//<?php echo $_ENV['HOST_IPV6'] . $_SERVER['REQUEST_URI']; ?>">IPv6</a></span><?php } ?>
    </div>
<?php } ?>
<main class="info">
    <h2>Your Connection</h2>
    <ul>
        <li>
            <label>IP Address</label>
            <span><?php echo $this->info->getIp(); ?></span>
        </li>
        <li>
            <label>Remote Host</label>
            <span><?php echo $this->info->getHost(); ?></span>
        </li>
        <li>
            <label>ASN</label>
            <span><?php echo $this->info->getAsn(); ?></span>
        </li>
        <li>
            <label>Country</label>
            <span><?php echo $this->getCountryString($this->info->getCountry()); ?></span>
        </li>
        <li>
            <label>City</label>
            <span><?php echo $this->info->getCity(); ?></span>
        </li>
        <li>
            <label>Postal</label>
            <span><?php echo $this->info->getPostal(); ?></span>
        </li>
        <li>
            <label>Subdivisions</label>
            <span><?php echo $this->getSubdivionsString($this->info->getSubdivisions()); ?></span>
        </li>
        <li>
            <label>Coordinates</label>
            <span><?php echo $this->getLocationString($this->info->getLocation()); ?></span>
        </li>
        <li>
            <label>Time Zone</label>
            <span><?php echo $this->info->getTimeZone(); ?></span>
        </li>
        <li>
            <label>Port</label>
            <span><?php echo $this->info->getPort(); ?></span>
        </li>
        <li>
            <label>Method</label>
            <span><?php echo $this->info->getMethod(); ?></span>
        </li>
        <li>
            <label>Referer</label>
            <span><?php echo $this->info->getReferer(); ?></span>
        </li>
        <li>
            <label>Headers</label>
            <span><?php echo $this->getHeadersHtml($this->info->getHeaders()); ?></span>
        </li>
    </ul>
</main>
