<?php if (getenv('HOST_AUTO') || getenv('HOST_IPV4') || getenv('HOST_IPV6')) { ?>
    <style>
        .force-ip {
            margin: 8px;
            position: absolute;
            right: 0;
            top: 0;
        }

        .force-ip span+span::before {
            content: " - ";
        }
    </style>
<?php } ?>
<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    li {
        border-top: 1px solid var(--border-color);
        display: flex;
        position: relative;
    }

    li>* {
        overflow: auto;
        padding: 8px;
    }

    label {
        display: inline-block;
        font-weight: bold;
        min-width: 140px;
    }

    button {
        background: url('data:image/svg+xml;base64,PHN2ZyBhcmlhLWhpZGRlbj0idHJ1ZSIgZm9jdXNhYmxlPSJmYWxzZSIgcm9sZT0iaW1nIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzODQgNTEyIj48cGF0aCBmaWxsPSJjdXJyZW50Q29sb3IiIGQ9Ik0zMzYgNjRoLTgwYzAtMzUuMy0yOC43LTY0LTY0LTY0cy02NCAyOC43LTY0IDY0SDQ4QzIxLjUgNjQgMCA4NS41IDAgMTEydjM1MmMwIDI2LjUgMjEuNSA0OCA0OCA0OGgyODhjMjYuNSAwIDQ4LTIxLjUgNDgtNDhWMTEyYzAtMjYuNS0yMS41LTQ4LTQ4LTQ4ek0xOTIgNDBjMTMuMyAwIDI0IDEwLjcgMjQgMjRzLTEwLjcgMjQtMjQgMjQtMjQtMTAuNy0yNC0yNCAxMC43LTI0IDI0LTI0em0xNDQgNDE4YzAgMy4zLTIuNyA2LTYgNkg1NGMtMy4zIDAtNi0yLjctNi02VjExOGMwLTMuMyAyLjctNiA2LTZoNDJ2MzZjMCA2LjYgNS40IDEyIDEyIDEyaDE2OGM2LjYgMCAxMi01LjQgMTItMTJ2LTM2aDQyYzMuMyAwIDYgMi43IDYgNnoiPjwvcGF0aD48L3N2Zz4=') center no-repeat;
        border: 0;
        cursor: pointer;
        display: none;
        height: 16px;
        margin: 8px 0;
        vertical-align: middle;
        width: 16px;
    }

    li.headers button {
        position: absolute;
        right: 8px;
    }

    li:hover button {
        display: initial;
    }

    span:empty::after {
        content: "-";
    }

    @media (max-width: 640px) {
        li {
            flex-direction: column;
        }

        label {
            padding-bottom: 4px;
        }

        span {
            padding-top: 0;
        }

        button {
            position: absolute;
            right: 8px;
        }
    }
</style>

<?php if (getenv('HOST_AUTO') || getenv('HOST_IPV4') || getenv('HOST_IPV6')) { ?>
    <div class="force-ip">
        <?php if (getenv('HOST_AUTO')) { ?><span><a href="//<?php echo getenv('HOST_AUTO') . $_SERVER['REQUEST_URI']; ?>">Auto</a></span><?php } ?>
        <?php if (getenv('HOST_IPV4')) { ?><span><a href="//<?php echo getenv('HOST_IPV4') . $_SERVER['REQUEST_URI']; ?>">IPv4</a></span><?php } ?>
        <?php if (getenv('HOST_IPV6')) { ?><span><a href="//<?php echo getenv('HOST_IPV6') . $_SERVER['REQUEST_URI']; ?>">IPv6</a></span><?php } ?>
    </div>
<?php } ?>
<main class="info">
    <h2>Your Connection</h2>
    <ul>
        <li>
            <label>IP Address</label>
            <span><?php echo $this->info->getIp(); ?></span>
        </li>
        <li>
            <label>Remote Host</label>
            <span><?php echo $this->info->getHost(); ?></span>
        </li>
        <li>
            <label>ASN</label>
            <span><?php echo $this->info->getAsn(); ?></span>
        </li>
        <li>
            <label>Country</label>
            <span><?php echo $this->getCountryString($this->info->getCountry()); ?></span>
        </li>
        <li>
            <label>City</label>
            <span><?php echo $this->info->getCity(); ?></span>
        </li>
        <li>
            <label>Postal</label>
            <span><?php echo $this->info->getPostal(); ?></span>
        </li>
        <li>
            <label>Subdivisions</label>
            <span><?php echo $this->getSubdivionsString($this->info->getSubdivisions()); ?></span>
        </li>
        <li>
            <label>Coordinates</label>
            <span><?php echo $this->getLocationString($this->info->getLocation()); ?></span>
        </li>
        <li>
            <label>Time Zone</label>
            <span><?php echo $this->info->getTimeZone(); ?></span>
        </li>
        <li>
            <label>Port</label>
            <span><?php echo $this->info->getPort(); ?></span>
        </li>
        <li>
            <label>Method</label>
            <span><?php echo $this->info->getMethod(); ?></span>
        </li>
        <li>
            <label>Referer</label>
            <span><?php echo $this->info->getReferer(); ?></span>
        </li>
        <li class="headers">
            <label>Headers</label>
            <span><?php echo $this->getHeadersHtml($this->info->getHeaders()); ?></span>
        </li>
    </ul>
</main>

<script>
    function copyText(node) {
        navigator.clipboard.writeText(node.textContent);
    }

    document.querySelectorAll('li').forEach(function(row) {
        const span = row.querySelector('span');
        if (!span.textContent) return;
        const copyButton = document.createElement('button');
        copyButton.classList.add('copy');
        row.appendChild(copyButton);
        copyButton.addEventListener('click', function() {
            copyText(span);
        });
    })
</script>
