<?php

$query = $this->getQuery();
$type = $this->getType();

function toFormatUri(string $format, string $query, ?string $type): string
{
    return '/?' .
        (!empty($query) ? 'q=' . $query . '&' : '') .
        (!empty($type) ? 'type=' . $type . '&' : '') .
        'format=' . $format;
}

if (getenv('HOST_AUTO') || getenv('HOST_IPV4') || getenv('HOST_IPV6')) { ?>
    <style>
        .force-ip {
            margin: var(--margin);
            position: absolute;
            right: 0;
            top: 0;
        }

        .force-ip span+span::before {
            content: " - ";
        }
    </style>
<?php } ?>
<style>
    form {
        display: flex;
        justify-content: center;
        margin-bottom: var(--margin);
    }

    input, select {
        color: var(--text-color);
        padding: var(--margin);
        border: 1px solid var(--border-color);
    }

    input[name=q] {
        background-color: var(--background-color);
        width: 400px;
        border-top-left-radius: var(--border-radius);
        border-bottom-left-radius: var(--border-radius);
    }

    select[name=ip] {
        background-color: var(--background-color-alt);
        margin-left: -1px;
    }

    input[type=submit] {
        background-color: var(--background-color-alt);
        margin-left: -1px;
        border-top-right-radius: var(--border-radius);
        border-bottom-right-radius: var(--border-radius);
        cursor: pointer;
    }

    h2 {
        display: flex;
    }

    h2 span {
        flex: 1;
    }

    h2 .links a {
        background-color: var(--blue-color);
        background-image: none;
        border-radius: 4px;
        color: var(--background-color);
        font-size: small;
        padding: 2px 4px;
        text-decoration: none;
        text-transform: uppercase;
    }

    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    li {
        display: flex;
        position: relative;
    }

    li+li {
        border-top: 1px solid var(--border-color);
    }

    li>* {
        overflow: auto;
        padding: var(--margin);
    }

    label {
        display: inline-block;
        font-weight: bold;
        min-width: 140px;
    }

    a[target="_blank"] {
        background-position: center right;
        background-repeat: no-repeat;
        background-image: linear-gradient(transparent, transparent), url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiID8+CjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTIiIGhlaWdodD0iMTIiPgoJPHBhdGggZmlsbD0iI2ZmZiIgc3Ryb2tlPSIjMzZjIiBkPSJNMS41IDQuNTE4aDUuOTgyVjEwLjVIMS41eiIgLz4KCTxwYXRoIGZpbGw9IiMzNmMiIGQ9Ik01Ljc2NSAxSDExdjUuMzlMOS40MjcgNy45MzdsLTEuMzEtMS4zMUw1LjM5MyA5LjM1bC0yLjY5LTIuNjg4IDIuODEtMi44MDhMNC4yIDIuNTQ0eiIgLz4KCTxwYXRoIGZpbGw9IiNmZmYiIGQ9Ik05Ljk5NSAyLjAwNGwuMDIyIDQuODg1TDguMiA1LjA3IDUuMzIgNy45NSA0LjA5IDYuNzIzbDIuODgyLTIuODgtMS44NS0xLjg1MnoiIC8+Cjwvc3ZnPgo=);
        padding-right: 16px;
    }

    button {
        background-color: var(--blue-color);;
        -webkit-mask: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzODQgNTEyIj48cGF0aCBkPSJNMzM2IDY0aC04MGMwLTM1LjMtMjguNy02NC02NC02NHMtNjQgMjguNy02NCA2NEg0OEMyMS41IDY0IDAgODUuNSAwIDExMnYzNTJjMCAyNi41IDIxLjUgNDggNDggNDhoMjg4YzI2LjUgMCA0OC0yMS41IDQ4LTQ4VjExMmMwLTI2LjUtMjEuNS00OC00OC00OHpNMTkyIDQwYzEzLjMgMCAyNCAxMC43IDI0IDI0cy0xMC43IDI0LTI0IDI0LTI0LTEwLjctMjQtMjQgMTAuNy0yNCAyNC0yNHptMTQ0IDQxOGMwIDMuMy0yLjcgNi02IDZINTRjLTMuMyAwLTYtMi43LTYtNlYxMThjMC0zLjMgMi43LTYgNi02aDQydjM2YzAgNi42IDUuNCAxMiAxMiAxMmgxNjhjNi42IDAgMTItNS40IDEyLTEydi0zNmg0MmMzLjMgMCA2IDIuNyA2IDZ6Ii8+PC9zdmc+') center no-repeat;
        mask: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzODQgNTEyIj48cGF0aCBkPSJNMzM2IDY0aC04MGMwLTM1LjMtMjguNy02NC02NC02NHMtNjQgMjguNy02NCA2NEg0OEMyMS41IDY0IDAgODUuNSAwIDExMnYzNTJjMCAyNi41IDIxLjUgNDggNDggNDhoMjg4YzI2LjUgMCA0OC0yMS41IDQ4LTQ4VjExMmMwLTI2LjUtMjEuNS00OC00OC00OHpNMTkyIDQwYzEzLjMgMCAyNCAxMC43IDI0IDI0cy0xMC43IDI0LTI0IDI0LTI0LTEwLjctMjQtMjQgMTAuNy0yNCAyNC0yNHptMTQ0IDQxOGMwIDMuMy0yLjcgNi02IDZINTRjLTMuMyAwLTYtMi43LTYtNlYxMThjMC0zLjMgMi43LTYgNi02aDQydjM2YzAgNi42IDUuNCAxMiAxMiAxMmgxNjhjNi42IDAgMTItNS40IDEyLTEydi0zNmg0MmMzLjMgMCA2IDIuNyA2IDZ6Ii8+PC9zdmc+') center no-repeat;
        border: 0;
        cursor: pointer;
        display: none;
        height: 16px;
        margin: var(--margin) 0;
        vertical-align: middle;
        width: 16px;
    }

    li.headers button {
        position: absolute;
        right: var(--margin);
    }

    li:hover button {
        display: initial;
    }

    li.copied button {
        -webkit-mask: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNy44MzcgMTcuODM3Ij48cGF0aCBkPSJNMTYuMTQ1IDIuNTcxYS43LjcgMCAwIDAtLjk5IDBMNi45MiAxMC44MDRsLTQuMjQxLTQuMjdhLjY5OC42OTggMCAwIDAtLjk4OSAwTC4yMDQgOC4wMTlhLjcwMy43MDMgMCAwIDAgMCAuOTlsNi4yMTcgNi4yNThhLjcwNC43MDQgMCAwIDAgLjk5IDBMMTcuNjMgNS4wNDdhLjcuNyAwIDAgMCAwLS45OTRsLTEuNDg1LTEuNDgyeiIvPjwvc3ZnPg==') center no-repeat;
        mask: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNy44MzcgMTcuODM3Ij48cGF0aCBkPSJNMTYuMTQ1IDIuNTcxYS43LjcgMCAwIDAtLjk5IDBMNi45MiAxMC44MDRsLTQuMjQxLTQuMjdhLjY5OC42OTggMCAwIDAtLjk4OSAwTC4yMDQgOC4wMTlhLjcwMy43MDMgMCAwIDAgMCAuOTlsNi4yMTcgNi4yNThhLjcwNC43MDQgMCAwIDAgLjk5IDBMMTcuNjMgNS4wNDdhLjcuNyAwIDAgMCAwLS45OTRsLTEuNDg1LTEuNDgyeiIvPjwvc3ZnPg==') center no-repeat;
        display: initial;
    }

    span:empty::after {
        content: "-";
    }

    @media (max-width: 640px) {
        input[name=q] {
            width: 100%;
        }

        h2 {
            flex-direction: column;
            text-align: center;
        }

        li {
            flex-direction: column;
        }

        label {
            padding-bottom: 4px;
        }

        span {
            padding-top: 0;
        }

        button {
            position: absolute;
            right: var(--margin);
        }
    }
</style>

<?php if (getenv('HOST_AUTO') || getenv('HOST_IPV4') || getenv('HOST_IPV6')) { ?>
    <div class="force-ip">
        <?php if (getenv('HOST_AUTO')) { ?><span><a href="//<?php echo getenv('HOST_AUTO') . $_SERVER['REQUEST_URI']; ?>">Auto</a></span><?php } ?>
        <?php if (getenv('HOST_IPV4')) { ?><span><a href="//<?php echo getenv('HOST_IPV4') . $_SERVER['REQUEST_URI']; ?>">IPv4</a></span><?php } ?>
        <?php if (getenv('HOST_IPV6')) { ?><span><a href="//<?php echo getenv('HOST_IPV6') . $_SERVER['REQUEST_URI']; ?>">IPv6</a></span><?php } ?>
    </div>
<?php } ?>
<form name="search" action="//<?= $_SERVER["HTTP_HOST"] ?>">
    <input type="text" name="q" placeholder="Search any IP Address, Host or URL" autofocus autocapitalize="off" value="<?= $query ?>">
    <select name="ip">
        <option value="">-</option>
        <option value="v4" <?= $type === 'v4' ? 'selected' : '' ?>>IPv4</option>
        <option value="v6" <?= $type === 'v6' ? 'selected' : '' ?>>IPv6</option>
    </select>
    <input type="submit" value="Search">
</form>
<main>
    <h2>
        <span><?= empty($query) ? "Your connection" : "$query information" ?></span>
        <div class="links">
            <a target="_blank" href="<?= toFormatUri('json', $query, $type) ?>">json</a>
            <a target="_blank" href="<?= toFormatUri('jsonp', $query, $type) ?>">jsonp</a>
            <a target="_blank" href="<?= toFormatUri('txt', $query, $type) ?>">txt</a>
            <a target="_blank" href="<?= toFormatUri('xml', $query, $type) ?>">xml</a>
            <a target="_blank" href="<?= toFormatUri('yaml', $query, $type) ?>">yaml</a>
        </div>
    </h2>
    <ul>
        <li>
            <label>IP Address</label>
            <span><?php echo $this->info->getIp(); ?></span>
        </li>
        <li>
            <label>Remote Host</label>
            <span><?php echo $this->info->getHost(); ?></span>
        </li>
        <li>
            <label>ASN</label>
            <span><?php echo $this->getAsnString($this->info->getAsn()); ?></span>
        </li>
        <li>
            <label>Country</label>
            <span><?php echo $this->getCountryString($this->info->getCountry()); ?></span>
        </li>
        <li>
            <label>City</label>
            <span><?php echo $this->info->getCity(); ?></span>
        </li>
        <li>
            <label>Postal</label>
            <span><?php echo $this->info->getPostal(); ?></span>
        </li>
        <li>
            <label>Subdivisions</label>
            <span><?php echo $this->getSubdivionsString($this->info->getSubdivisions()); ?></span>
        </li>
        <li>
            <label>Coordinates</label>
            <span><?php echo $this->getLocationString($this->info->getLocation()); ?></span>
        </li>
        <li>
            <label>Time Zone</label>
            <span><?php echo $this->info->getTimeZone(); ?></span>
        </li>
        <li>
            <label>Port</label>
            <span><?php echo $this->info->getPort(); ?></span>
        </li>
        <li>
            <label>Method</label>
            <span><?php echo $this->info->getMethod(); ?></span>
        </li>
        <li>
            <label>Referer</label>
            <span><?php echo $this->info->getReferer(); ?></span>
        </li>
        <li class="headers">
            <label>Headers</label>
            <span><?php echo $this->getHeadersHtml($this->info->getHeaders()); ?></span>
        </li>
    </ul>
</main>

<script>
    function copyText(node) {
        navigator.clipboard.writeText(node.innerHTML.replaceAll('<br>', '\n').replaceAll(/<.*?>/g, ''));
    }

    function acknowledgeCopy(row, button) {
        window.clearTimeout(button.copiedTimeout);
        row.classList.add('copied');
        row.copiedTimeout = window.setTimeout(function() {
            row.classList.remove('copied');
        }, 2000);
    }

    function handleCopy(row, span) {
        const button = document.createElement('button');
        button.classList.add('copy');
        row.appendChild(button);
        button.addEventListener('click', function() {
            copyText(span);
            acknowledgeCopy(row, button);
        });
    }

    document.querySelectorAll('li').forEach(function(row) {
        const span = row.querySelector('span');
        if (!span.textContent) return;
        handleCopy(row, span);
    });
</script>
