<?php

define('THOUSAND_SEPARATOR', true);

if (!extension_loaded('Zend OPcache')) {
    echo '<div style="background-color: #F2DEDE; color: #B94A48; padding: 1em;">You do not have the Zend OPcache extension loaded, sample data is being shown instead.</div>';
}

class OpCacheDataModel
{
    private $configuration;
    private $status;
    private $d3Scripts = array();

    public function __construct()
    {
        $this->configuration = opcache_get_configuration();
        $this->status = opcache_get_status();
    }

    public function getPageTitle()
    {
        return 'PHP ' . phpversion() . " with OpCache {$this->configuration['version']['version']}";
    }

    public function getStatusDataRows()
    {
        $rows = array();
        foreach ($this->status as $key => $value) {
            if ($key === 'scripts') {
                continue;
            }

            if (is_array($value)) {
                foreach ($value as $k => $v) {
                    if ($v === false) {
                        $value = 'false';
                    }
                    if ($v === true) {
                        $value = 'true';
                    }
                    if ($k === 'used_memory' || $k === 'free_memory' || $k === 'wasted_memory') {
                        $v = $this->toHumanSize($v);
                    }
                    if ($k === 'current_wasted_percentage' || $k === 'opcache_hit_rate') {
                        $v = number_format($v, 2) . '%';
                    }
                    if ($k === 'blacklist_miss_ratio') {
                        $v = number_format($v, 2) . '%';
                    }
                    if ($k === 'start_time' || $k === 'last_restart_time') {
                        $v = ($v ? date(DATE_RFC822, $v) : 'never');
                    }
                    if (THOUSAND_SEPARATOR === true && is_int($v)) {
                        $v = number_format($v);
                    }
                    $rows[] = "<tr><th>$k</th><td>$v</td></tr>\n";
                }
                continue;
            }
            if ($value === false) {
                $value = 'false';
            }
            if ($value === true) {
                $value = 'true';
            }
            $rows[] = "<tr><th>$key</th><td>$value</td></tr>\n";
        }

        return implode("\n", $rows);
    }

    public function getConfigDataRows()
    {
        $rows = array();
        foreach ($this->configuration['directives'] as $key => $value) {
            if ($value === false) {
                $value = 'false';
            }
            if ($value === true) {
                $value = 'true';
            }
            if ($key == 'opcache.memory_consumption') {
                $value = $this->toHumanSize($value);
            }
            $rows[] = "<tr><th>$key</th><td>$value</td></tr>\n";
        }

        return implode("\n", $rows);
    }

    public function getScriptStatusRows()
    {
        foreach ($this->status['scripts'] as $key => $data) {
            $dirs[dirname($key)][basename($key)] = $data;
            $this->withPset($this->d3Scripts, $key, array(
                'name' => basename($key),
                'size' => $data['memory_consumption'],
            ));
        }
        asort($dirs);
        $basename = '';
        while (true) {
            if (count($this->d3Scripts) !== 1) break;
            $basename .= DIRECTORY_SEPARATOR . key($this->d3Scripts);
            $this->d3Scripts = reset($this->d3Scripts);
        }
        $this->d3Scripts = $this->processPartition($this->d3Scripts, $basename);
        $id = 1;
        $rows = array();
        foreach ($dirs as $dir => $files) {
            $count = count($files);
            $plural = $count > 1 ? 's' : null;
            $memory = 0;
            foreach ($files as $file => $data) {
                $memory += $data["memory_consumption"];
            }
            $memory = $this->toHumanSize($memory);
            if ($count > 1) {
                $rows[] = '<tr>';
                $rows[] = "<th class=\"clickable\" id=\"head-{$id}\" colspan=\"3\" onclick=\"toggleVisible('#head-{$id}', '#row-{$id}')\">{$dir} ({$count} file{$plural}, {$memory})</th>";
                $rows[] = '</tr>';
            }
            foreach ($files as $file => $data) {
                $rows[] = "<tr id=\"row-{$id}\">";
                $rows[] = "<td>" . $this->formatValue($data["hits"]) . "</td>";
                $rows[] = "<td>" . $this->toHumanSize($data["memory_consumption"]) . "</td>";
                $rows[] = $count > 1 ? "<td>{$file}</td>" : "<td>{$dir}/{$file}</td>";
                $rows[] = '</tr>';
            }
            $id++;
        }
        return implode("\n", $rows);
    }

    public function getScriptStatusCount()
    {
        return count($this->status["scripts"]);
    }

    public function getGraphDataSetJson()
    {
        $dataset = array();
        $dataset['memory'] = array(
            $this->status['memory_usage']['used_memory'],
            $this->status['memory_usage']['free_memory'],
            $this->status['memory_usage']['wasted_memory'],
        );
        $dataset['keys'] = array(
            $this->status['opcache_statistics']['num_cached_keys'],
            $this->status['opcache_statistics']['max_cached_keys'] - $this->status['opcache_statistics']['num_cached_keys'],
            0
        );
        $dataset['hits'] = array(
            $this->status['opcache_statistics']['misses'],
            $this->status['opcache_statistics']['hits'],
            0,
        );
        $dataset['restarts'] = array(
            $this->status['opcache_statistics']['oom_restarts'],
            $this->status['opcache_statistics']['manual_restarts'],
            $this->status['opcache_statistics']['hash_restarts'],
        );
        $dataset['TSEP'] = THOUSAND_SEPARATOR === true ? 1 : 0;
        return json_encode($dataset);
    }

    public function getHumanUsedMemory()
    {
        return $this->toHumanSize($this->getUsedMemory());
    }

    public function getHumanFreeMemory()
    {
        return $this->toHumanSize($this->getFreeMemory());
    }

    public function getHumanWastedMemory()
    {
        return $this->toHumanSize($this->getWastedMemory());
    }

    public function getUsedMemory()
    {
        return $this->status['memory_usage']['used_memory'];
    }

    public function getFreeMemory()
    {
        return $this->status['memory_usage']['free_memory'];
    }

    public function getWastedMemory()
    {
        return $this->status['memory_usage']['wasted_memory'];
    }

    public function getWastedMemoryPercentage()
    {
        return number_format($this->status['memory_usage']['current_wasted_percentage'], 2);
    }

    public function getD3Scripts()
    {
        return $this->d3Scripts;
    }

    private function processPartition($value, $name = null)
    {
        if (array_key_exists('size', $value)) {
            return $value;
        }
        $array = array('name' => $name, 'children' => array());
        foreach ($value as $k => $v) {
            $array['children'][] = $this->processPartition($v, $k);
        }
        return $array;
    }

    private function formatValue($value)
    {
        if (THOUSAND_SEPARATOR === true) {
            return number_format($value);
        } else {
            return $value;
        }
    }

    private function toHumanSize($bytes)
    {
        if ($bytes > 1048576) {
            return sprintf('%.2f&nbsp;MB', $bytes / 1048576);
        }
        if ($bytes > 1024) {
            return sprintf('%.2f&nbsp;kB', $bytes / 1024);
        }
        return sprintf('%d&nbsp;bytes', $bytes);
    }

    private function withPset(&$array, $key, $value)
    {
        if (is_null($key)) return $array = $value;
        $keys = explode(DIRECTORY_SEPARATOR, ltrim($key, DIRECTORY_SEPARATOR));
        while (count($keys) > 1) {
            $key = array_shift($keys);
            if (!isset($array[$key]) || !is_array($array[$key])) {
                $array[$key] = array();
            }
            $array = &$array[$key];
        }
        $array[array_shift($keys)] = $value;
        return $array;
    }
}

$dataModel = new OpCacheDataModel();
?>
<div>
    <style>
        #container {
            display: flex;
            position: relative;
            width: 100%;
            margin: auto;
        }

        table {
            border-collapse: collapse;
        }

        tbody tr:nth-child(even) {
            background-color: #eee;
        }

        p.capitalize {
            text-transform: capitalize;
        }

        .tabs {
            flex: 1;
            display: flex;
            flex-direction: column;
        }

        .tabs-headers {
            display: flex;
            z-index: 1;
        }

        .tab-header {
            display: flex;
            flex-direction: column;
        }

        .tab-header label {
            background: #eee;
            padding: 10px 12px;
            border: 1px solid #ccc;
            margin-right: -1px;
            margin-bottom: -1px;
        }

        .tab-header [type=radio] {
            display: none;
        }

        .tab-content thead th {
            position: sticky;
            top: 0;
            background-color: black;
            color: white;
        }

        .tab-content th,
        .tab-content td {
            padding: 8px 12px;
        }

        .tab-content {
            background: white;
            border: 1px solid #ccc;
            height: 450px;
            max-width: 100%;
            overflow-x: hidden;
            overflow-y: auto;
        }

        .tab-content:not(#tab-status--content) {
            display: none;
        }

        .tab-content table {
            width: 100%;
        }

        .tab-content th,
        .tab:nth-child(3) td {
            text-align: left;
        }

        .tab-content td {
            text-align: right;
        }

        .clickable {
            cursor: pointer;
        }

        [type=radio]:checked~label {
            background: white;
            border-bottom: 1px solid white;
        }

        [type=radio]:checked~label~.tab-content {
            display: initial;
        }

        #graph {
            position: relative;
            width: 400px;
        }

        #graph>form {
            position: absolute;
            right: 60px;
            top: -20px;
        }

        #graph>svg {
            position: absolute;
            top: 0;
            right: 0;
        }

        #stats {
            position: absolute;
            right: 125px;
            top: 145px;
        }

        #stats th,
        #stats td {
            padding: 6px 10px;
            font-size: 0.8em;
        }

        #partition {
            position: fixed;
            width: 100%;
            height: 100%;
            z-index: 10;
            top: 0;
            left: 0;
            background: #ddd;
            display: none;
        }

        #close-partition {
            display: none;
            position: fixed;
            z-index: 20;
            right: 15px;
            top: 15px;
            background: #f9373d;
            color: #fff;
            padding: 12px 15px;
        }

        #close-partition:hover {
            background: #D32F33;
            cursor: pointer;
        }

        #partition rect {
            stroke: #fff;
            fill: #aaa;
            fill-opacity: 1;
        }

        #partition rect.parent {
            cursor: pointer;
            fill: steelblue;
        }

        #partition text {
            pointer-events: none;
        }

        label {
            cursor: pointer;
        }

        .clear {
            clear: both;
        }
    </style>
    <h3><?php echo $dataModel->getPageTitle(); ?></h3>
    <div id="container">
        <div class="tabs">
            <div class="tabs-headers">
                <div class="tab-header">
                    <input type="radio" id="tab-status" name="tab-group" checked>
                    <label for="tab-status">Status</label>
                </div>
                <div class="tab-header">
                    <input type="radio" id="tab-config" name="tab-group">
                    <label for="tab-config">Configuration</label>
                </div>
                <div class="tab-header">
                    <input type="radio" id="tab-scripts" name="tab-group">
                    <label for="tab-scripts">Scripts (<?php echo $dataModel->getScriptStatusCount(); ?>)</label>
                </div>
                <div class="tab-header">
                    <input type="radio" id="tab-visualise" name="tab-group">
                    <label for="tab-visualise">Visualise Partition</label>
                </div>
            </div>

            <div class="tab-content" id="tab-status--content">
                <table>
                    <?php echo $dataModel->getStatusDataRows(); ?>
                </table>
            </div>
            <div class="tab-content" id="tab-config--content">
                <table>
                    <?php echo $dataModel->getConfigDataRows(); ?>
                </table>
            </div>
            <div class="tab-content" id="tab-scripts--content">
                <table>
                    <thead>
                        <tr>
                            <th width="10%">Hits</th>
                            <th width="20%">Memory</th>
                            <th width="70%">Path</th>
                        </tr>
                    </thead>
                    <?php echo $dataModel->getScriptStatusRows(); ?>
                </table>
            </div>
            <div class="tab-content" id="tab-visualise--content"></div>
        </div>
        <div id="graph">
            <form>
                <label><input type="radio" name="dataset" value="memory" checked> Memory</label>
                <label><input type="radio" name="dataset" value="keys"> Keys</label>
                <label><input type="radio" name="dataset" value="hits"> Hits</label>
                <label><input type="radio" name="dataset" value="restarts"> Restarts</label>
            </form>
            <div id="stats"></div>
        </div>
    </div>
    <div id="close-partition">&#10006; Close Visualisation</div>
    <div id="partition"></div>
    <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.0.1/d3.v3.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>
        let hidden = {};

        function toggleVisible(head, row) {
            if (!hidden[row]) {
                d3.selectAll(row).transition().style('display', 'none');
                hidden[row] = true;
                d3.select(head).transition().style('color', '#ccc');
            } else {
                d3.selectAll(row).transition().style('display');
                hidden[row] = false;
                d3.select(head).transition().style('color', '#000');
            }
        }

        let dataset = <?php echo $dataModel->getGraphDataSetJson(); ?>;
        let width = 400,
            height = 400,
            radius = Math.min(width, height) / 2,
            colours = ['#B41F1F', '#1FB437', '#ff7f0e'];
        d3.scale.customColours = function() {
            return d3.scale.ordinal().range(colours);
        };
        let colour = d3.scale.customColours();
        let pie = d3.layout.pie().sort(null);
        let arc = d3.svg.arc().innerRadius(radius - 20).outerRadius(radius - 50);
        let svg = d3.select("#graph").append("svg")
            .attr("width", width)
            .attr("height", height)
            .append("g")
            .attr("transform", "translate(" + width / 2 + "," + height / 2 + ")");
        let path = svg.selectAll("path")
            .data(pie(dataset.memory))
            .enter().append("path")
            .attr("fill", function(d, i) {
                return colour(i);
            })
            .attr("d", arc)
            .each(function(d) {
                this.current = d;
            });

        d3.selectAll("input").on("change", change);
        set_text("memory");

        function set_text(t) {
            if (t === "memory") {
                d3.select("#stats").html(
                    "<table><tr><th style='background:#B41F1F;'>Used</th><td><?php echo $dataModel->getHumanUsedMemory() ?></td></tr>" +
                    "<tr><th style='background:#1FB437;'>Free</th><td><?php echo $dataModel->getHumanFreeMemory() ?></td></tr>" +
                    "<tr><th style='background:#ff7f0e;' rowspan=\"2\">Wasted</th><td><?php echo $dataModel->getHumanWastedMemory() ?></td></tr>" +
                    "<tr><td><?php echo $dataModel->getWastedMemoryPercentage() ?>%</td></tr></table>"
                );
            } else if (t === "keys") {
                d3.select("#stats").html(
                    "<table><tr><th style='background:#B41F1F;'>Cached keys</th><td>" + format_value(dataset[t][0]) + "</td></tr>" +
                    "<tr><th style='background:#1FB437;'>Free Keys</th><td>" + format_value(dataset[t][1]) + "</td></tr></table>"
                );
            } else if (t === "hits") {
                d3.select("#stats").html(
                    "<table><tr><th style='background:#B41F1F;'>Misses</th><td>" + format_value(dataset[t][0]) + "</td></tr>" +
                    "<tr><th style='background:#1FB437;'>Cache Hits</th><td>" + format_value(dataset[t][1]) + "</td></tr></table>"
                );
            } else if (t === "restarts") {
                d3.select("#stats").html(
                    "<table><tr><th style='background:#B41F1F;'>Memory</th><td>" + dataset[t][0] + "</td></tr>" +
                    "<tr><th style='background:#1FB437;'>Manual</th><td>" + dataset[t][1] + "</td></tr>" +
                    "<tr><th style='background:#ff7f0e;'>Keys</th><td>" + dataset[t][2] + "</td></tr></table>"
                );
            }
        }

        function change() {
            if (!dataset[this.value]) return;
            let removeZeroValues = dataset[this.value].filter(function(value) {
                return value > 0;
            });
            if (typeof dataset[this.value] !== 'undefined' && removeZeroValues.length > 0) {
                $('#graph').find('> svg').show();
                path = path.data(pie(dataset[this.value]));
                path.transition().duration(750).attrTween("d", arcTween);
            } else {
                $('#graph').find('> svg').hide();
            }
            set_text(this.value);
        }

        function arcTween(a) {
            let i = d3.interpolate(this.current, a);
            this.current = i(0);
            return function(t) {
                return arc(i(t));
            };
        }

        function size_for_humans(bytes) {
            if (bytes > 1048576) {
                return (bytes / 1048576).toFixed(2) + ' MB';
            } else if (bytes > 1024) {
                return (bytes / 1024).toFixed(2) + ' KB';
            } else return bytes + ' bytes';
        }

        function format_value(value) {
            return dataset["TSEP"] == 1 ?
                value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") :
                value;
        }

        let w = window.innerWidth,
            h = window.innerHeight,
            x = d3.scale.linear().range([0, w]),
            y = d3.scale.linear().range([0, h]);
        let vis = d3.select("#partition")
            .append("svg:svg")
            .attr("width", w)
            .attr("height", h);
        let partition = d3.layout.partition()
            .value(function(d) {
                return d.size;
            });
        root = JSON.parse('<?php echo json_encode($dataModel->getD3Scripts()); ?>');
        let g = vis.selectAll("g")
            .data(partition.nodes(root))
            .enter().append("svg:g")
            .attr("transform", function(d) {
                return "translate(" + x(d.y) + "," + y(d.x) + ")";
            })
            .on("click", click);
        let kx = w / root.dx,
            ky = h / 1;
        g.append("svg:rect")
            .attr("width", root.dy * kx)
            .attr("height", function(d) {
                return d.dx * ky;
            })
            .attr("class", function(d) {
                return d.children ? "parent" : "child";
            });
        g.append("svg:text")
            .attr("transform", transform)
            .attr("dy", ".35em")
            .style("opacity", function(d) {
                return d.dx * ky > 12 ? 1 : 0;
            })
            .text(function(d) {
                return d.name;
            })
        d3.select(window)
            .on("click", function() {
                click(root);
            })

        function click(d) {
            if (!d.children) return;
            kx = (d.y ? w - 40 : w) / (1 - d.y);
            ky = h / d.dx;
            x.domain([d.y, 1]).range([d.y ? 40 : 0, w]);
            y.domain([d.x, d.x + d.dx]);
            let t = g.transition()
                .duration(d3.event.altKey ? 7500 : 750)
                .attr("transform", function(d) {
                    return "translate(" + x(d.y) + "," + y(d.x) + ")";
                });
            t.select("rect")
                .attr("width", d.dy * kx)
                .attr("height", function(d) {
                    return d.dx * ky;
                });
            t.select("text")
                .attr("transform", transform)
                .style("opacity", function(d) {
                    return d.dx * ky > 12 ? 1 : 0;
                });
            d3.event.stopPropagation();
        }

        function transform(d) {
            return "translate(8, " + d.dx * ky / 2 + ")";
        }

        $(document).ready(function() {
            $('[name=tab-group]').on('change', function() {
                const id = $(this).attr('id');
                $('.tab-content').hide();
                $(`.tab-content#${id}--content`).show();

            });

            function handleVisualisationToggle(close) {
                $('#partition, #close-partition').fadeToggle();
                // if (close) {
                //     $('#tab-visualise').removeAttr('checked');
                //     $('#tab-status').trigger('click');
                // }
            }
            $('label[for="tab-visualise"], #close-partition').on('click', function() {
                handleVisualisationToggle(($(this).attr('id') === 'close-partition'));
                return false;
            });
            $(document).keyup(function(e) {
                if (e.keyCode == 27) handleVisualisationToggle(true);
            });
        });
    </script>
    <div class="clear"></div>
</div>
